@env = dev
@API_HostAddress = http://localhost:5000/api
@get_email = {{email}}
@get_password = {{password}}

# @name loginRequest
POST {{API_HostAddress}}/auth/login
Content-Type: application/json

{
  "email": "{{get_email}}",
  "password": "{{get_password}}"
}

###
@accessToken = {{loginRequest.response.body.token}}
GET {{API_HostAddress}}/records
Authorization: {{token}}

###


