// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using RecordTracker.Infrastructure.Persistence;

#nullable disable

namespace RecordTracker.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(RecordTrackerDbContext))]
    partial class RecordTrackerDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("RecordTracker.Infrastructure.Entities.RecordField", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("FieldType")
                        .HasColumnType("integer");

                    b.Property<bool>("IsRequired")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.Property<Guid>("RecordTypeId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("RecordTypeId");

                    b.ToTable("RecordField", (string)null);
                });

            modelBuilder.Entity("RecordTracker.Infrastructure.Entities.RecordItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RecordTypeId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("RecordTypeId");

                    b.ToTable("RecordItem", (string)null);
                });

            modelBuilder.Entity("RecordTracker.Infrastructure.Entities.RecordType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByUserId");

                    b.ToTable("RecordType", (string)null);
                });

            modelBuilder.Entity("RecordTracker.Infrastructure.Entities.RecordValue", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("RecordFieldId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RecordItemId")
                        .HasColumnType("uuid");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RecordFieldId");

                    b.HasIndex("RecordItemId");

                    b.ToTable("RecordValue", (string)null);
                });

            modelBuilder.Entity("RecordTracker.Infrastructure.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("User", (string)null);
                });

            modelBuilder.Entity("RecordTracker.Infrastructure.Entities.RecordField", b =>
                {
                    b.HasOne("RecordTracker.Infrastructure.Entities.RecordType", "RecordType")
                        .WithMany("RecordFields")
                        .HasForeignKey("RecordTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RecordType");
                });

            modelBuilder.Entity("RecordTracker.Infrastructure.Entities.RecordItem", b =>
                {
                    b.HasOne("RecordTracker.Infrastructure.Entities.User", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("RecordTracker.Infrastructure.Entities.RecordType", "RecordType")
                        .WithMany("RecordItems")
                        .HasForeignKey("RecordTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CreatedByUser");

                    b.Navigation("RecordType");
                });

            modelBuilder.Entity("RecordTracker.Infrastructure.Entities.RecordType", b =>
                {
                    b.HasOne("RecordTracker.Infrastructure.Entities.User", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("CreatedByUser");
                });

            modelBuilder.Entity("RecordTracker.Infrastructure.Entities.RecordValue", b =>
                {
                    b.HasOne("RecordTracker.Infrastructure.Entities.RecordField", "RecordField")
                        .WithMany("RecordValues")
                        .HasForeignKey("RecordFieldId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RecordTracker.Infrastructure.Entities.RecordItem", "RecordItem")
                        .WithMany("RecordValues")
                        .HasForeignKey("RecordItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RecordField");

                    b.Navigation("RecordItem");
                });

            modelBuilder.Entity("RecordTracker.Infrastructure.Entities.RecordField", b =>
                {
                    b.Navigation("RecordValues");
                });

            modelBuilder.Entity("RecordTracker.Infrastructure.Entities.RecordItem", b =>
                {
                    b.Navigation("RecordValues");
                });

            modelBuilder.Entity("RecordTracker.Infrastructure.Entities.RecordType", b =>
                {
                    b.Navigation("RecordFields");

                    b.Navigation("RecordItems");
                });
#pragma warning restore 612, 618
        }
    }
}
